owner: Inktomi93
repo: inktomitech_uptime

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true
  - name: Authentik Domain
    url: https://authentik.inktomi.tech
  - name: OpenWebUI
    url: https://openwebui.inktomi.tech
  - name: Pi-hole
    url: https://pihole.inktomi.tech
  - name: SillyTavern
    url: https://sillytavern.inktomi.tech
  - name: StirlingPDF
    url: https://stirlingpdf.inktomi.tech
  - name: TabbyAPI
    url: https://tabbyapi.inktomi.tech
  - name: vLLM
    url: https://vllm.inktomi.tech
  - name: ComfyUI
    url: https://comfyui.inktomi.tech
  - name: Portainer
    url: https://portainer.inktomi.tech

status-website:
  # cname: demo.upptime.js.org
  baseUrl: /inktomitech_uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: InktomiTech Status Monitor
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
